// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block_index.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BlockIndexORM struct {
	Number int64 `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (BlockIndexORM) TableName() string {
	return "block_indices"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *BlockIndex) ToORM(ctx context.Context) (BlockIndexORM, error) {
	to := BlockIndexORM{}
	var err error
	if prehook, ok := interface{}(m).(BlockIndexWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	if posthook, ok := interface{}(m).(BlockIndexWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BlockIndexORM) ToPB(ctx context.Context) (BlockIndex, error) {
	to := BlockIndex{}
	var err error
	if prehook, ok := interface{}(m).(BlockIndexWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	if posthook, ok := interface{}(m).(BlockIndexWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type BlockIndex the arg will be the target, the caller the one being converted from

// BlockIndexBeforeToORM called before default ToORM code
type BlockIndexWithBeforeToORM interface {
	BeforeToORM(context.Context, *BlockIndexORM) error
}

// BlockIndexAfterToORM called after default ToORM code
type BlockIndexWithAfterToORM interface {
	AfterToORM(context.Context, *BlockIndexORM) error
}

// BlockIndexBeforeToPB called before default ToPB code
type BlockIndexWithBeforeToPB interface {
	BeforeToPB(context.Context, *BlockIndex) error
}

// BlockIndexAfterToPB called after default ToPB code
type BlockIndexWithAfterToPB interface {
	AfterToPB(context.Context, *BlockIndex) error
}

// DefaultCreateBlockIndex executes a basic gorm create call
func DefaultCreateBlockIndex(ctx context.Context, in *BlockIndex, db *gorm1.DB) (*BlockIndex, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockIndexORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockIndexORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BlockIndexORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockIndexORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBlockIndex patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBlockIndex(ctx context.Context, patchee *BlockIndex, patcher *BlockIndex, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*BlockIndex, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBlockIndex executes a gorm list call
func DefaultListBlockIndex(ctx context.Context, db *gorm1.DB) ([]*BlockIndex, error) {
	in := BlockIndex{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockIndexORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BlockIndexORM{}, &BlockIndex{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockIndexORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("number")
	ormResponse := []BlockIndexORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockIndexORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*BlockIndex{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BlockIndexORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockIndexORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockIndexORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BlockIndexORM) error
}
