package models

import (
	context "context"
	errors "github.com/infobloxopen/protoc-gen-gorm/errors"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	gorm "gorm.io/gorm"
)

type KafkaJobORM struct {
	JobId       string `gorm:"primaryKey"`
	Partition   uint64 `gorm:"primaryKey"`
	StopOffset  uint64
	Topic       string `gorm:"primaryKey"`
	WorkerGroup string `gorm:"primaryKey"`
}

// TableName overrides the default tablename generated by GORM
func (KafkaJobORM) TableName() string {
	return "kafka_jobs"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *KafkaJob) ToORM(ctx context.Context) (KafkaJobORM, error) {
	to := KafkaJobORM{}
	var err error
	if prehook, ok := interface{}(m).(KafkaJobWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.JobId = m.JobId
	to.WorkerGroup = m.WorkerGroup
	to.Topic = m.Topic
	to.Partition = m.Partition
	to.StopOffset = m.StopOffset
	if posthook, ok := interface{}(m).(KafkaJobWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *KafkaJobORM) ToPB(ctx context.Context) (KafkaJob, error) {
	to := KafkaJob{}
	var err error
	if prehook, ok := interface{}(m).(KafkaJobWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.JobId = m.JobId
	to.WorkerGroup = m.WorkerGroup
	to.Topic = m.Topic
	to.Partition = m.Partition
	to.StopOffset = m.StopOffset
	if posthook, ok := interface{}(m).(KafkaJobWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type KafkaJob the arg will be the target, the caller the one being converted from

// KafkaJobBeforeToORM called before default ToORM code
type KafkaJobWithBeforeToORM interface {
	BeforeToORM(context.Context, *KafkaJobORM) error
}

// KafkaJobAfterToORM called after default ToORM code
type KafkaJobWithAfterToORM interface {
	AfterToORM(context.Context, *KafkaJobORM) error
}

// KafkaJobBeforeToPB called before default ToPB code
type KafkaJobWithBeforeToPB interface {
	BeforeToPB(context.Context, *KafkaJob) error
}

// KafkaJobAfterToPB called after default ToPB code
type KafkaJobWithAfterToPB interface {
	AfterToPB(context.Context, *KafkaJob) error
}

// DefaultCreateKafkaJob executes a basic gorm create call
func DefaultCreateKafkaJob(ctx context.Context, in *KafkaJob, db *gorm.DB) (*KafkaJob, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Omit().Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type KafkaJobORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type KafkaJobORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm.DB) error
}

func DefaultReadKafkaJob(ctx context.Context, in *KafkaJob, db *gorm.DB) (*KafkaJob, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.JobId == "" {
		return nil, errors.EmptyIdError
	}
	if ormObj.Partition == 0 {
		return nil, errors.EmptyIdError
	}
	if ormObj.Topic == "" {
		return nil, errors.EmptyIdError
	}
	if ormObj.WorkerGroup == "" {
		return nil, errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := KafkaJobORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(KafkaJobORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type KafkaJobORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type KafkaJobORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type KafkaJobORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm.DB) error
}

func DefaultDeleteKafkaJob(ctx context.Context, in *KafkaJob, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.JobId == "" {
		return errors.EmptyIdError
	}
	if ormObj.Partition == 0 {
		return errors.EmptyIdError
	}
	if ormObj.Topic == "" {
		return errors.EmptyIdError
	}
	if ormObj.WorkerGroup == "" {
		return errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&KafkaJobORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type KafkaJobORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type KafkaJobORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm.DB) error
}

// DefaultApplyFieldMaskKafkaJob patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskKafkaJob(ctx context.Context, patchee *KafkaJob, patcher *KafkaJob, updateMask *field_mask.FieldMask, prefix string, db *gorm.DB) (*KafkaJob, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"JobId" {
			patchee.JobId = patcher.JobId
			continue
		}
		if f == prefix+"WorkerGroup" {
			patchee.WorkerGroup = patcher.WorkerGroup
			continue
		}
		if f == prefix+"Topic" {
			patchee.Topic = patcher.Topic
			continue
		}
		if f == prefix+"Partition" {
			patchee.Partition = patcher.Partition
			continue
		}
		if f == prefix+"StopOffset" {
			patchee.StopOffset = patcher.StopOffset
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListKafkaJob executes a gorm list call
func DefaultListKafkaJob(ctx context.Context, db *gorm.DB) ([]*KafkaJob, error) {
	in := KafkaJob{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("job_id, partition, topic, worker_group")
	ormResponse := []KafkaJobORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(KafkaJobORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*KafkaJob{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type KafkaJobORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type KafkaJobORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type KafkaJobORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm.DB, *[]KafkaJobORM) error
}
