package models

import (
	context "context"
	fmt "fmt"
	errors "github.com/infobloxopen/protoc-gen-gorm/errors"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	gorm "gorm.io/gorm"
)

type MissingBlockORM struct {
	Number int64 `gorm:"primaryKey"`
}

// TableName overrides the default tablename generated by GORM
func (MissingBlockORM) TableName() string {
	return "missing_blocks"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *MissingBlock) ToORM(ctx context.Context) (MissingBlockORM, error) {
	to := MissingBlockORM{}
	var err error
	if prehook, ok := interface{}(m).(MissingBlockWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	if posthook, ok := interface{}(m).(MissingBlockWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *MissingBlockORM) ToPB(ctx context.Context) (MissingBlock, error) {
	to := MissingBlock{}
	var err error
	if prehook, ok := interface{}(m).(MissingBlockWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	if posthook, ok := interface{}(m).(MissingBlockWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type MissingBlock the arg will be the target, the caller the one being converted from

// MissingBlockBeforeToORM called before default ToORM code
type MissingBlockWithBeforeToORM interface {
	BeforeToORM(context.Context, *MissingBlockORM) error
}

// MissingBlockAfterToORM called after default ToORM code
type MissingBlockWithAfterToORM interface {
	AfterToORM(context.Context, *MissingBlockORM) error
}

// MissingBlockBeforeToPB called before default ToPB code
type MissingBlockWithBeforeToPB interface {
	BeforeToPB(context.Context, *MissingBlock) error
}

// MissingBlockAfterToPB called after default ToPB code
type MissingBlockWithAfterToPB interface {
	AfterToPB(context.Context, *MissingBlock) error
}

// DefaultCreateMissingBlock executes a basic gorm create call
func DefaultCreateMissingBlock(ctx context.Context, in *MissingBlock, db *gorm.DB) (*MissingBlock, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Omit().Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type MissingBlockORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm.DB) error
}

func DefaultReadMissingBlock(ctx context.Context, in *MissingBlock, db *gorm.DB) (*MissingBlock, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.Number == 0 {
		return nil, errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := MissingBlockORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(MissingBlockORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type MissingBlockORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm.DB) error
}

func DefaultDeleteMissingBlock(ctx context.Context, in *MissingBlock, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.Number == 0 {
		return errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&MissingBlockORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type MissingBlockORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm.DB) error
}

func DefaultDeleteMissingBlockSet(ctx context.Context, in []*MissingBlock, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	var err error
	keys := []int64{}
	for _, obj := range in {
		ormObj, err := obj.ToORM(ctx)
		if err != nil {
			return err
		}
		if ormObj.Number == 0 {
			return errors.EmptyIdError
		}
		keys = append(keys, ormObj.Number)
	}
	if hook, ok := (interface{}(&MissingBlockORM{})).(MissingBlockORMWithBeforeDeleteSet); ok {
		if db, err = hook.BeforeDeleteSet(ctx, in, db); err != nil {
			return err
		}
	}
	err = db.Where("number in (?)", keys).Delete(&MissingBlockORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := (interface{}(&MissingBlockORM{})).(MissingBlockORMWithAfterDeleteSet); ok {
		err = hook.AfterDeleteSet(ctx, in, db)
	}
	return err
}

type MissingBlockORMWithBeforeDeleteSet interface {
	BeforeDeleteSet(context.Context, []*MissingBlock, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithAfterDeleteSet interface {
	AfterDeleteSet(context.Context, []*MissingBlock, *gorm.DB) error
}

// DefaultStrictUpdateMissingBlock clears / replaces / appends first level 1:many children and then executes a gorm update call
func DefaultStrictUpdateMissingBlock(ctx context.Context, in *MissingBlock, db *gorm.DB) (*MissingBlock, error) {
	if in == nil {
		return nil, fmt.Errorf("Nil argument to DefaultStrictUpdateMissingBlock")
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	lockedRow := &MissingBlockORM{}
	db.Model(&ormObj).Set("gorm:query_option", "FOR UPDATE").Where("number=?", ormObj.Number).First(lockedRow)
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeStrictUpdateCleanup); ok {
		if db, err = hook.BeforeStrictUpdateCleanup(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeStrictUpdateSave); ok {
		if db, err = hook.BeforeStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Omit().Save(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithAfterStrictUpdateSave); ok {
		if err = hook.AfterStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	return &pbResponse, err
}

type MissingBlockORMWithBeforeStrictUpdateCleanup interface {
	BeforeStrictUpdateCleanup(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithBeforeStrictUpdateSave interface {
	BeforeStrictUpdateSave(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithAfterStrictUpdateSave interface {
	AfterStrictUpdateSave(context.Context, *gorm.DB) error
}

// DefaultPatchMissingBlock executes a basic gorm update call with patch behavior
func DefaultPatchMissingBlock(ctx context.Context, in *MissingBlock, updateMask *field_mask.FieldMask, db *gorm.DB) (*MissingBlock, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	var pbObj MissingBlock
	var err error
	if hook, ok := interface{}(&pbObj).(MissingBlockWithBeforePatchRead); ok {
		if db, err = hook.BeforePatchRead(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&pbObj).(MissingBlockWithBeforePatchApplyFieldMask); ok {
		if db, err = hook.BeforePatchApplyFieldMask(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if _, err := DefaultApplyFieldMaskMissingBlock(ctx, &pbObj, in, updateMask, "", db); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&pbObj).(MissingBlockWithBeforePatchSave); ok {
		if db, err = hook.BeforePatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := DefaultStrictUpdateMissingBlock(ctx, &pbObj, db)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(pbResponse).(MissingBlockWithAfterPatchSave); ok {
		if err = hook.AfterPatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	return pbResponse, nil
}

type MissingBlockWithBeforePatchRead interface {
	BeforePatchRead(context.Context, *MissingBlock, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockWithBeforePatchApplyFieldMask interface {
	BeforePatchApplyFieldMask(context.Context, *MissingBlock, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockWithBeforePatchSave interface {
	BeforePatchSave(context.Context, *MissingBlock, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockWithAfterPatchSave interface {
	AfterPatchSave(context.Context, *MissingBlock, *field_mask.FieldMask, *gorm.DB) error
}

// DefaultPatchSetMissingBlock executes a bulk gorm update call with patch behavior
func DefaultPatchSetMissingBlock(ctx context.Context, objects []*MissingBlock, updateMasks []*field_mask.FieldMask, db *gorm.DB) ([]*MissingBlock, error) {
	if len(objects) != len(updateMasks) {
		return nil, fmt.Errorf(errors.BadRepeatedFieldMaskTpl, len(updateMasks), len(objects))
	}

	results := make([]*MissingBlock, 0, len(objects))
	for i, patcher := range objects {
		pbResponse, err := DefaultPatchMissingBlock(ctx, patcher, updateMasks[i], db)
		if err != nil {
			return nil, err
		}

		results = append(results, pbResponse)
	}

	return results, nil
}

// DefaultApplyFieldMaskMissingBlock patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskMissingBlock(ctx context.Context, patchee *MissingBlock, patcher *MissingBlock, updateMask *field_mask.FieldMask, prefix string, db *gorm.DB) (*MissingBlock, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListMissingBlock executes a gorm list call
func DefaultListMissingBlock(ctx context.Context, db *gorm.DB) ([]*MissingBlock, error) {
	in := MissingBlock{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("number")
	ormResponse := []MissingBlockORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*MissingBlock{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type MissingBlockORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type MissingBlockORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm.DB, *[]MissingBlockORM) error
}
