// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: missing_block.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type MissingBlockORM struct {
	Number int64 `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (MissingBlockORM) TableName() string {
	return "missing_blocks"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *MissingBlock) ToORM(ctx context.Context) (MissingBlockORM, error) {
	to := MissingBlockORM{}
	var err error
	if prehook, ok := interface{}(m).(MissingBlockWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	if posthook, ok := interface{}(m).(MissingBlockWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *MissingBlockORM) ToPB(ctx context.Context) (MissingBlock, error) {
	to := MissingBlock{}
	var err error
	if prehook, ok := interface{}(m).(MissingBlockWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	if posthook, ok := interface{}(m).(MissingBlockWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type MissingBlock the arg will be the target, the caller the one being converted from

// MissingBlockBeforeToORM called before default ToORM code
type MissingBlockWithBeforeToORM interface {
	BeforeToORM(context.Context, *MissingBlockORM) error
}

// MissingBlockAfterToORM called after default ToORM code
type MissingBlockWithAfterToORM interface {
	AfterToORM(context.Context, *MissingBlockORM) error
}

// MissingBlockBeforeToPB called before default ToPB code
type MissingBlockWithBeforeToPB interface {
	BeforeToPB(context.Context, *MissingBlock) error
}

// MissingBlockAfterToPB called after default ToPB code
type MissingBlockWithAfterToPB interface {
	AfterToPB(context.Context, *MissingBlock) error
}

// DefaultCreateMissingBlock executes a basic gorm create call
func DefaultCreateMissingBlock(ctx context.Context, in *MissingBlock, db *gorm1.DB) (*MissingBlock, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type MissingBlockORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type MissingBlockORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskMissingBlock patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskMissingBlock(ctx context.Context, patchee *MissingBlock, patcher *MissingBlock, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*MissingBlock, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListMissingBlock executes a gorm list call
func DefaultListMissingBlock(ctx context.Context, db *gorm1.DB) ([]*MissingBlock, error) {
	in := MissingBlock{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &MissingBlockORM{}, &MissingBlock{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("number")
	ormResponse := []MissingBlockORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(MissingBlockORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*MissingBlock{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type MissingBlockORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type MissingBlockORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type MissingBlockORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]MissingBlockORM) error
}
