// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: redis_key.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type RedisKeyORM struct {
	Key   string `gorm:"primary_key"`
	Value string
}

// TableName overrides the default tablename generated by GORM
func (RedisKeyORM) TableName() string {
	return "redis_keys"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *RedisKey) ToORM(ctx context.Context) (RedisKeyORM, error) {
	to := RedisKeyORM{}
	var err error
	if prehook, ok := interface{}(m).(RedisKeyWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Key = m.Key
	to.Value = m.Value
	if posthook, ok := interface{}(m).(RedisKeyWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *RedisKeyORM) ToPB(ctx context.Context) (RedisKey, error) {
	to := RedisKey{}
	var err error
	if prehook, ok := interface{}(m).(RedisKeyWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Key = m.Key
	to.Value = m.Value
	if posthook, ok := interface{}(m).(RedisKeyWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type RedisKey the arg will be the target, the caller the one being converted from

// RedisKeyBeforeToORM called before default ToORM code
type RedisKeyWithBeforeToORM interface {
	BeforeToORM(context.Context, *RedisKeyORM) error
}

// RedisKeyAfterToORM called after default ToORM code
type RedisKeyWithAfterToORM interface {
	AfterToORM(context.Context, *RedisKeyORM) error
}

// RedisKeyBeforeToPB called before default ToPB code
type RedisKeyWithBeforeToPB interface {
	BeforeToPB(context.Context, *RedisKey) error
}

// RedisKeyAfterToPB called after default ToPB code
type RedisKeyWithAfterToPB interface {
	AfterToPB(context.Context, *RedisKey) error
}

// DefaultCreateRedisKey executes a basic gorm create call
func DefaultCreateRedisKey(ctx context.Context, in *RedisKey, db *gorm1.DB) (*RedisKey, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(RedisKeyORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(RedisKeyORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type RedisKeyORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type RedisKeyORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskRedisKey patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskRedisKey(ctx context.Context, patchee *RedisKey, patcher *RedisKey, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*RedisKey, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Key" {
			patchee.Key = patcher.Key
			continue
		}
		if f == prefix+"Value" {
			patchee.Value = patcher.Value
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListRedisKey executes a gorm list call
func DefaultListRedisKey(ctx context.Context, db *gorm1.DB) ([]*RedisKey, error) {
	in := RedisKey{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(RedisKeyORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &RedisKeyORM{}, &RedisKey{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(RedisKeyORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("key")
	ormResponse := []RedisKeyORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(RedisKeyORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*RedisKey{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type RedisKeyORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type RedisKeyORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type RedisKeyORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]RedisKeyORM) error
}
