package models

import (
	context "context"
	fmt "fmt"
	gorm1 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm "github.com/jinzhu/gorm"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
)

type TokenAddressORM struct {
	Address              string  `gorm:"primary_key"`
	Balance              float64 `gorm:"index:token_address_idx_balance"`
	TokenContractAddress string  `gorm:"primary_key;index:token_address_idx_token_contract_address"`
}

// TableName overrides the default tablename generated by GORM
func (TokenAddressORM) TableName() string {
	return "token_addresses"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *TokenAddress) ToORM(ctx context.Context) (TokenAddressORM, error) {
	to := TokenAddressORM{}
	var err error
	if prehook, ok := interface{}(m).(TokenAddressWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.TokenContractAddress = m.TokenContractAddress
	to.Balance = m.Balance
	if posthook, ok := interface{}(m).(TokenAddressWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TokenAddressORM) ToPB(ctx context.Context) (TokenAddress, error) {
	to := TokenAddress{}
	var err error
	if prehook, ok := interface{}(m).(TokenAddressWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Address = m.Address
	to.TokenContractAddress = m.TokenContractAddress
	to.Balance = m.Balance
	if posthook, ok := interface{}(m).(TokenAddressWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type TokenAddress the arg will be the target, the caller the one being converted from

// TokenAddressBeforeToORM called before default ToORM code
type TokenAddressWithBeforeToORM interface {
	BeforeToORM(context.Context, *TokenAddressORM) error
}

// TokenAddressAfterToORM called after default ToORM code
type TokenAddressWithAfterToORM interface {
	AfterToORM(context.Context, *TokenAddressORM) error
}

// TokenAddressBeforeToPB called before default ToPB code
type TokenAddressWithBeforeToPB interface {
	BeforeToPB(context.Context, *TokenAddress) error
}

// TokenAddressAfterToPB called after default ToPB code
type TokenAddressWithAfterToPB interface {
	AfterToPB(context.Context, *TokenAddress) error
}

// DefaultCreateTokenAddress executes a basic gorm create call
func DefaultCreateTokenAddress(ctx context.Context, in *TokenAddress, db *gorm.DB) (*TokenAddress, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TokenAddressORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm.DB) error
}

func DefaultReadTokenAddress(ctx context.Context, in *TokenAddress, db *gorm.DB) (*TokenAddress, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.Address == "" {
		return nil, errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if db, err = gorm1.ApplyFieldSelection(ctx, db, nil, &TokenAddressORM{}); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := TokenAddressORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(TokenAddressORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type TokenAddressORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm.DB) error
}

func DefaultDeleteTokenAddress(ctx context.Context, in *TokenAddress, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.Address == "" {
		return errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&TokenAddressORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type TokenAddressORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm.DB) error
}

func DefaultDeleteTokenAddressSet(ctx context.Context, in []*TokenAddress, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	var err error
	keys := []string{}
	for _, obj := range in {
		ormObj, err := obj.ToORM(ctx)
		if err != nil {
			return err
		}
		if ormObj.Address == "" {
			return errors.EmptyIdError
		}
		keys = append(keys, ormObj.Address)
	}
	if hook, ok := (interface{}(&TokenAddressORM{})).(TokenAddressORMWithBeforeDeleteSet); ok {
		if db, err = hook.BeforeDeleteSet(ctx, in, db); err != nil {
			return err
		}
	}
	err = db.Where("address in (?)", keys).Delete(&TokenAddressORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := (interface{}(&TokenAddressORM{})).(TokenAddressORMWithAfterDeleteSet); ok {
		err = hook.AfterDeleteSet(ctx, in, db)
	}
	return err
}

type TokenAddressORMWithBeforeDeleteSet interface {
	BeforeDeleteSet(context.Context, []*TokenAddress, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithAfterDeleteSet interface {
	AfterDeleteSet(context.Context, []*TokenAddress, *gorm.DB) error
}

// DefaultStrictUpdateTokenAddress clears / replaces / appends first level 1:many children and then executes a gorm update call
func DefaultStrictUpdateTokenAddress(ctx context.Context, in *TokenAddress, db *gorm.DB) (*TokenAddress, error) {
	if in == nil {
		return nil, fmt.Errorf("Nil argument to DefaultStrictUpdateTokenAddress")
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	lockedRow := &TokenAddressORM{}
	db.Model(&ormObj).Set("gorm:query_option", "FOR UPDATE").Where("address=?", ormObj.Address).First(lockedRow)
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeStrictUpdateCleanup); ok {
		if db, err = hook.BeforeStrictUpdateCleanup(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeStrictUpdateSave); ok {
		if db, err = hook.BeforeStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Save(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithAfterStrictUpdateSave); ok {
		if err = hook.AfterStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	return &pbResponse, err
}

type TokenAddressORMWithBeforeStrictUpdateCleanup interface {
	BeforeStrictUpdateCleanup(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithBeforeStrictUpdateSave interface {
	BeforeStrictUpdateSave(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithAfterStrictUpdateSave interface {
	AfterStrictUpdateSave(context.Context, *gorm.DB) error
}

// DefaultPatchTokenAddress executes a basic gorm update call with patch behavior
func DefaultPatchTokenAddress(ctx context.Context, in *TokenAddress, updateMask *field_mask.FieldMask, db *gorm.DB) (*TokenAddress, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	var pbObj TokenAddress
	var err error
	if hook, ok := interface{}(&pbObj).(TokenAddressWithBeforePatchRead); ok {
		if db, err = hook.BeforePatchRead(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&pbObj).(TokenAddressWithBeforePatchApplyFieldMask); ok {
		if db, err = hook.BeforePatchApplyFieldMask(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if _, err := DefaultApplyFieldMaskTokenAddress(ctx, &pbObj, in, updateMask, "", db); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&pbObj).(TokenAddressWithBeforePatchSave); ok {
		if db, err = hook.BeforePatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := DefaultStrictUpdateTokenAddress(ctx, &pbObj, db)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(pbResponse).(TokenAddressWithAfterPatchSave); ok {
		if err = hook.AfterPatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	return pbResponse, nil
}

type TokenAddressWithBeforePatchRead interface {
	BeforePatchRead(context.Context, *TokenAddress, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressWithBeforePatchApplyFieldMask interface {
	BeforePatchApplyFieldMask(context.Context, *TokenAddress, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressWithBeforePatchSave interface {
	BeforePatchSave(context.Context, *TokenAddress, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressWithAfterPatchSave interface {
	AfterPatchSave(context.Context, *TokenAddress, *field_mask.FieldMask, *gorm.DB) error
}

// DefaultPatchSetTokenAddress executes a bulk gorm update call with patch behavior
func DefaultPatchSetTokenAddress(ctx context.Context, objects []*TokenAddress, updateMasks []*field_mask.FieldMask, db *gorm.DB) ([]*TokenAddress, error) {
	if len(objects) != len(updateMasks) {
		return nil, fmt.Errorf(errors.BadRepeatedFieldMaskTpl, len(updateMasks), len(objects))
	}

	results := make([]*TokenAddress, 0, len(objects))
	for i, patcher := range objects {
		pbResponse, err := DefaultPatchTokenAddress(ctx, patcher, updateMasks[i], db)
		if err != nil {
			return nil, err
		}

		results = append(results, pbResponse)
	}

	return results, nil
}

// DefaultApplyFieldMaskTokenAddress patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTokenAddress(ctx context.Context, patchee *TokenAddress, patcher *TokenAddress, updateMask *field_mask.FieldMask, prefix string, db *gorm.DB) (*TokenAddress, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Address" {
			patchee.Address = patcher.Address
			continue
		}
		if f == prefix+"TokenContractAddress" {
			patchee.TokenContractAddress = patcher.TokenContractAddress
			continue
		}
		if f == prefix+"Balance" {
			patchee.Balance = patcher.Balance
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTokenAddress executes a gorm list call
func DefaultListTokenAddress(ctx context.Context, db *gorm.DB) ([]*TokenAddress, error) {
	in := TokenAddress{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm1.ApplyCollectionOperators(ctx, db, &TokenAddressORM{}, &TokenAddress{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("address")
	ormResponse := []TokenAddressORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TokenAddressORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*TokenAddress{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TokenAddressORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TokenAddressORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm.DB, *[]TokenAddressORM) error
}
