name: pr-test

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bring up DBs
        run: |
          make up-dbs
          make ps 

      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Run tests
        run: cd src && go test ./... -v
