name: pr-test

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bring up DBs
        run: make up-dbs

      - name: Check DBs
        run: make ps

      - name: Run tests
        run: cd src && go test ./... -v

      - name: Bring up stack
        run: make up

      - name: Check stack
        run: make ps

      - name: Run tests
        run: cd tests && go test ./... -v
