name: push-main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'chart/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Go mod tidy
        run: cd src && go mod tidy

      - name: Bring up DBs
        run: make up-dbs

      - name: Check DBs
        run: make ps

      - name: Run tests
        run: cd src && go test ./... -v

      - name: Bring up stack
        run: make up && sleep 10

      - name: Check stack
        run: make ps

#     - name: Go mod tidy
#       run: cd tests && go mod tidy

#     - name: Run tests
#       run: cd tests && go test ./... -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: icon-transformer
          IMAGE_TAG: dev-${{ github.run_number }}
        run: |
          docker build --target prod -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
