name: push-main-dockerhub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Go mod tidy
        run: cd src && go mod tidy

      - name: Bring up DBs
        run: make up-dbs

      - name: Check DBs
        run: make ps

      - name: Run tests
        run: cd src && go test ./... -v

      - name: Bring up stack
        run: make up && sleep 10

      - name: Check stack
        run: make ps

#     - name: Go mod tidy
#       run: cd tests && go mod tidy

#     - name: Run tests
#       run: cd tests && go test ./... -v

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: sudoblock/icon-transformer

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: prod
          push: true
          tags: sudoblock/icon-transformer:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: prod
          push: true
          tags: sudoblock/icon-transformer:${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
